from server import handle_move

# from typing import List, Dict

# import math
# import operator
# from operator import add

# import random as rand
import numpy as np
# # import pandas as pd
# # import random as rand
# import copy as copy

# import time as time
# from logClass import log

import constants as CONST
# import functions as fn

# from snakeClass import snake
# from boardClass import board


# test_routes = [{data}, 'up', {data}, 'down']
# for test_data in test_routes  
#   data = data[0]
#   expected = data[1] 
#   # load data
#   # make move 
# data

route_data_survive = [
    [1, 'right','survive - chase tail instead of food',{'game': {'id': '8c202d0a-e493-4f3a-acc0-26b875d83c03', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 66, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_CytDcCKwYKvWQgcSjDbb7dG8', 'name': 'idzol cloud', 'latency': '240', 'health': 89, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 6}, {'x': 10, 'y': 5}, {'x': 10, 'y': 4}, {'x': 10, 'y': 3}], 'head': {'x': 6, 'y': 8}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_DGxwC3CFxH4jj4f6bhp7PVRD', 'name': 'vomc', 'latency': '181', 'health': 92, 'body': [{'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}], 'head': {'x': 4, 'y': 8}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_QGGGTBmP6phdFSB8CTpyjSt4', 'name': 'nates_python', 'latency': '182', 'health': 76, 'body': [{'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 7, 'y': 9}, {'x': 7, 'y': 10}, {'x': 8, 'y': 10}, {'x': 9, 'y': 10}, {'x': 10, 'y': 10}, {'x': 10, 'y': 9}, {'x': 9, 'y': 9}], 'head': {'x': 5, 'y': 9}, 'length': 9, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 2}, {'x': 5, 'y': 8}], 'hazards': []}, 'you': {'id': 'gs_CytDcCKwYKvWQgcSjDbb7dG8', 'name': 'idzol cloud', 'latency': '240', 'health': 89, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 6}, {'x': 10, 'y': 5}, {'x': 10, 'y': 4}, {'x': 10, 'y': 3}], 'head': {'x': 6, 'y': 8}, 'length': 12, 'shout': '', 'squad': ''}}],
    [2, 'down', 'enemy strategy - one move to kill',{'game': {'id': 'd433023a-fb47-4fc3-9ec1-a30f694e4793', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 96, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_CCCpvxKBwPvRJM9G96dgXK3Q', 'name': 'idzol cloud', 'latency': '213', 'health': 73, 'body': [{'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}], 'head': {'x': 8, 'y': 2}, 'length': 9, 'shout': '', 'squad': ''}, {'id': 'gs_TDtcxGgVmxWmFvdhbySqwGfD', 'name': '>:3', 'latency': '402', 'health': 4, 'body': [{'x': 9, 'y': 1}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}], 'head': {'x': 9, 'y': 1}, 'length': 3, 'shout': '', 'squad': ''}, {'id': 'gs_KdSCHFc3pyhQ3PcYyXTWfpMY', 'name': 'Brainiac', 'latency': '255', 'health': 67, 'body': [{'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}], 'head': {'x': 2, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_8MRGqW6FmMKBQYfFcgqTH9pR', 'name': 'Super Snakey', 'latency': '206', 'health': 92, 'body': [{'x': 1, 'y': 3}, {'x': 1, 'y': 2}, {'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 7, 'y': 1}, {'x': 7, 'y': 2}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}], 'head': {'x': 1, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}], 'food': [{'x': 1, 'y': 9}, {'x': 4, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_CCCpvxKBwPvRJM9G96dgXK3Q', 'name': 'idzol cloud', 'latency': '213', 'health': 73, 'body': [{'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}], 'head': {'x': 8, 'y': 2}, 'length': 9, 'shout': '', 'squad': ''}}],
    [3, 'down', 'route selection - certain death vs possible death', {'game': {'id': '932cf8ae-de0c-4e63-a89d-7b259f886deb', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 143, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_DrdpjkdQSmFm6KGYwq7hJVHV', 'name': 'SnakeJS', 'latency': '192', 'health': 98, 'body': [{'x': 0, 'y': 7}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}], 'head': {'x': 0, 'y': 7}, 'length': 16, 'shout': '[1 7] --> [0 6]', 'squad': ''}], 'food': [{'x': 0, 'y': 6}, {'x': 1, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}}],
    [4, 'down', 'enemy strategy - two moves to kill', {'game': {'id': 'c105689d-eb47-4e18-ac97-ed6eb234969b', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 80, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_jCJpyKGpjvRVmQ7WYRRcgwkH', 'name': 'idzol cloud', 'latency': '218', 'health': 99, 'body': [{'x': 3, 'y': 9}, {'x': 3, 'y': 10}, {'x': 4, 'y': 10}, {'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}], 'head': {'x': 3, 'y': 9}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_CfjhM4RXS6KmGTjgtSbMqFR7', 'name': 'Swiss Cheese', 'latency': '180', 'health': 100, 'body': [{'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 8, 'y': 8}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 5, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_qg7DcGJ336mhwcGdRRPJHwTX', 'name': 'BobFrit Jr', 'latency': '196', 'health': 91, 'body': [{'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}], 'head': {'x': 2, 'y': 8}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 3, 'y': 5}, {'x': 5, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_jCJpyKGpjvRVmQ7WYRRcgwkH', 'name': 'idzol cloud', 'latency': '218', 'health': 99, 'body': [{'x': 3, 'y': 9}, {'x': 3, 'y': 10}, {'x': 4, 'y': 10}, {'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}], 'head': {'x': 3, 'y': 9}, 'length': 13, 'shout': '', 'squad': ''}}],
    [5, 'up', 'enemy strategy - one move to kill', {'game': {'id': '61a48f68-8588-4994-a352-1df2021ad1e0', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 50, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_3CQG3SSptjCQTGGHkkBJMq7W', 'name': 'idzol cloud', 'latency': '225', 'health': 89, 'body': [{'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}], 'head': {'x': 10, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_t4KdPyYK6h8BP4wphwv3rRc7', 'name': 'icedostrich', 'latency': '101', 'health': 78, 'body': [{'x': 9, 'y': 1}, {'x': 9, 'y': 2}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}], 'head': {'x': 9, 'y': 1}, 'length': 7, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 1}, {'x': 10, 'y': 1}, {'x': 2, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_3CQG3SSptjCQTGGHkkBJMq7W', 'name': 'idzol cloud', 'latency': '225', 'health': 89, 'body': [{'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}], 'head': {'x': 10, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}}],
    [6,'right', 'enemy strategy - two moves to kill', {'game': {'id': '1d057583-a2e7-4e97-ae8c-c33d8ee26433', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 121, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_FBjRfqRPG9DVcyWXjJ3MM799', 'name': 'idzol cloud', 'latency': '158', 'health': 90, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 13, 'shout': 'Thou hast no more brain than I have in mine elbows', 'squad': ''}, {'id': 'gs_YdQRfWGtbH7RqSVww8Hq9fVX', 'name': 'SnakeJS', 'latency': '174', 'health': 98, 'body': [{'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 6, 'y': 2}, {'x': 6, 'y': 1}, {'x': 5, 'y': 1}, {'x': 4, 'y': 1}, {'x': 3, 'y': 1}, {'x': 2, 'y': 1}, {'x': 1, 'y': 1}, {'x': 1, 'y': 2}, {'x': 0, 'y': 2}], 'head': {'x': 3, 'y': 8}, 'length': 18, 'shout': '[4 8] --> [3 10]', 'squad': ''}], 'food': [{'x': 7, 'y': 7}, {'x': 3, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_FBjRfqRPG9DVcyWXjJ3MM799', 'name': 'idzol cloud', 'latency': '158', 'health': 90, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 13, 'shout': 'Thou hast no more brain than I have in mine elbows', 'squad': ''}}],
    [7,'left', 'enemy intent - get food', {'game': {'id': '8ee4149a-7e3a-423f-b86f-96ef19bd4192', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 109, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_94jrfYxKtvV97bHfcDKWVTg3', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}, {'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 2, 'y': 0}, {'x': 1, 'y': 0}], 'head': {'x': 1, 'y': 10}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_krxgMMYGv6ggtvJKtcFwwktR', 'name': 'Blake', 'latency': '213', 'health': 91, 'body': [{'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 6, 'y': 2}, {'x': 7, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}], 'head': {'x': 4, 'y': 7}, 'length': 14, 'shout': '', 'squad': ''}], 'food': [{'x': 4, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_94jrfYxKtvV97bHfcDKWVTg3', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}, {'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 2, 'y': 0}, {'x': 1, 'y': 0}], 'head': {'x': 1, 'y': 10}, 'length': 13, 'shout': '', 'squad': ''}}],
    [8,'up', 'enemy eating - certain death vs possible death ', {'game': {'id': '39f5f3fb-c456-4924-9abe-54117b608a12', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 32, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}, {'id': 'gs_CgyqbSwvKSphK6VRmHxrCWVW', 'name': 'moon-snake-pika', 'latency': '192', 'health': 89, 'body': [{'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 3, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}], 'head': {'x': 1, 'y': 7}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_B3hBgh8SfRXd9dtdff7CQT6F', 'name': 'starter_snake', 'latency': '235', 'health': 100, 'body': [{'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 4}], 'head': {'x': 0, 'y': 6}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}}],
    [9,'down', 'control area - safe board vs danger board', {'game': {'id': 'f76091b1-b5de-4e83-86b7-3119c9d76b0c', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 121, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_4kcXvqwTSKMRtH8MRPTdxSbK', 'name': 'idzol cloud', 'latency': '233', 'health': 100, 'body': [{'x': 10, 'y': 7}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 3, 'y': 3}], 'head': {'x': 10, 'y': 7}, 'length': 13, 'shout': 'Art thou a flesh-monger, a fool and a coward?', 'squad': ''}, {'id': 'gs_Ky9PfwF8CV6vVvKvSDJG8d46', 'name': 'CorneliusCodes', 'latency': '71', 'health': 93, 'body': [{'x': 5, 'y': 10}, {'x': 4, 'y': 10}, {'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}, {'x': 1, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 10, 'shout': '', 'squad': ''}], 'food': [{'x': 1, 'y': 1}, {'x': 2, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_4kcXvqwTSKMRtH8MRPTdxSbK', 'name': 'idzol cloud', 'latency': '233', 'health': 100, 'body': [{'x': 10, 'y': 7}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 3, 'y': 3}], 'head': {'x': 10, 'y': 7}, 'length': 13, 'shout': 'Art thou a flesh-monger, a fool and a coward?', 'squad': ''}}],
    [10,'right', 'enemy killcut - us eating and larger', {'game': {'id': 'dd09ebb2-bdeb-4b81-b76b-428817007c85', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 51, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_JR7C8rvVFfFydBH8XBhTQd9D', 'name': 'idzol cloud', 'latency': '237', 'health': 100, 'body': [{'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 7}], 'head': {'x': 7, 'y': 10}, 'length': 9, 'shout': 'Thou art as fat as butter', 'squad': ''}, {'id': 'gs_v7cWbF7WhCq6k8JmyMc6BXyB', 'name': 'Eve', 'latency': '182', 'health': 51, 'body': [{'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 0, 'y': 10}], 'head': {'x': 3, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_JTFWcPF4bw7DpW6f36pVDbqb', 'name': 'SnakeJS', 'latency': '181', 'health': 94, 'body': [{'x': 1, 'y': 4}, {'x': 0, 'y': 4}, {'x': 0, 'y': 5}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}], 'head': {'x': 1, 'y': 4}, 'length': 9, 'shout': '[0 4] --> [5 7]', 'squad': ''}], 'food': [{'x': 5, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_JR7C8rvVFfFydBH8XBhTQd9D', 'name': 'idzol cloud', 'latency': '237', 'health': 100, 'body': [{'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 7}], 'head': {'x': 7, 'y': 10}, 'length': 9, 'shout': 'Thou art as fat as butter', 'squad': ''}}],
    [11,'up', 'enemy killcut - ignore food and see danger', {'game': {'id': '2cad3115-593c-46a5-8165-841121466f24', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 92, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_VmWcGyCRgy44VRYgdccdY9KQ', 'name': 'idzol cloud', 'latency': '322', 'health': 100, 'body': [{'x': 0, 'y': 2}, {'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 2, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 7}], 'head': {'x': 0, 'y': 2}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_TPhGwH7RwCGCTX6fXPBgSwM7', 'name': 'Swiss Cheese', 'latency': '180', 'health': 78, 'body': [{'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}, {'x': 6, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}], 'head': {'x': 9, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_7c3QYx43ycBdBJw9WV38XQxQ', 'name': 'Potoooooooo', 'latency': '2', 'health': 67, 'body': [{'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'head': {'x': 5, 'y': 1}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 1}, {'x': 7, 'y': 7}, {'x': 3, 'y': 0}], 'hazards': []}, 'you': {'id': 'gs_VmWcGyCRgy44VRYgdccdY9KQ', 'name': 'idzol cloud', 'latency': '322', 'health': 100, 'body': [{'x': 0, 'y': 2}, {'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 2, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 7}], 'head': {'x': 0, 'y': 2}, 'length': 12, 'shout': '', 'squad': ''}}],
    [12,'right', 'survive - see path through tail', {'game': {'id': '42bfec7b-2dc2-417a-af9d-a0c1f08cb323', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 191, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_fkHXpHg3QG6pJyjdBk9FWmRM', 'name': 'idzol cloud', 'latency': '206', 'health': 61, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 9, 'y': 2}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'head': {'x': 9, 'y': 10}, 'length': 22, 'shout': 'You are as a candle, the better burnt out.', 'squad': ''}, {'id': 'gs_b8CcJvjVWv3CvMwxXyt3dfKf', 'name': 'Jack of all Snakes', 'latency': '188', 'health': 84, 'body': [{'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 10, 'shout': '', 'squad': ''}], 'food': [{'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 6, 'y': 8}, {'x': 5, 'y': 3}], 'hazards': []}, 'you': {'id': 'gs_fkHXpHg3QG6pJyjdBk9FWmRM', 'name': 'idzol cloud', 'latency': '206', 'health': 61, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 9, 'y': 2}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'head': {'x': 9, 'y': 10}, 'length': 22, 'shout': 'You are as a candle, the better burnt out.', 'squad': ''}}],
    [13,'left', 'control area - safe board vs danger board', {'game': {'id': 'b3b743ef-6e91-489d-8e3a-89221897a54f', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 141, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_XCYgxFhjV4yKvyrH6tJYj4p4', 'name': 'idzol cloud', 'latency': '207', 'health': 86, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 3, 'y': 10}, 'length': 14, 'shout': 'Thou elvish-mark’d, abortive, rooting hog!', 'squad': ''}, {'id': 'gs_M7kmgFmhr8wG8jQrhphSpW4X', 'name': 'soba', 'latency': '47', 'health': 87, 'body': [{'x': 2, 'y': 7}, {'x': 3, 'y': 7}, {'x': 4, 'y': 7}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 5, 'y': 4}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 8, 'y': 2}, {'x': 8, 'y': 1}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 6, 'y': 0}, {'x': 5, 'y': 0}], 'head': {'x': 2, 'y': 7}, 'length': 17, 'shout': 'chasing snack', 'squad': ''}], 'food': [{'x': 0, 'y': 9}, {'x': 3, 'y': 2}, {'x': 2, 'y': 10}, {'x': 10, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_XCYgxFhjV4yKvyrH6tJYj4p4', 'name': 'idzol cloud', 'latency': '207', 'health': 86, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 3, 'y': 10}, 'length': 14, 'shout': 'Thou elvish-mark’d, abortive, rooting hog!', 'squad': ''}}],
    [14,'up', 'enemy killcut - 100 percent chance to kill', {'game': {'id': '3b7a1097-2e87-4515-973a-43b68843da01', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 104, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_hyhjDjFpSySxTGXRGc8yvDC8', 'name': 'GGGelo', 'latency': '209', 'health': 90, 'body': [{'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}, {'x': 5, 'y': 7}], 'head': {'x': 9, 'y': 5}, 'length': 11, 'shout': "It'ssss over my friend", 'squad': ''}, {'id': 'gs_w4HMHv8GSbhjhVDg3BWRhd9C', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 3, 'y': 2}, {'x': 2, 'y': 2}, {'x': 1, 'y': 2}, {'x': 1, 'y': 3}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}], 'head': {'x': 10, 'y': 2}, 'length': 13, 'shout': '', 'squad': ''}], 'food': [{'x': 10, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_w4HMHv8GSbhjhVDg3BWRhd9C', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 3, 'y': 2}, {'x': 2, 'y': 2}, {'x': 1, 'y': 2}, {'x': 1, 'y': 3}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}], 'head': {'x': 10, 'y': 2}, 'length': 13, 'shout': '', 'squad': ''}}],
    # [15,'', '', {}],
    # [16,'', '', {}],
]

route_data_attack = [
    [101,'up', 'headon collision - ignore tail and smaller', {'game': {'id': '6871f4f4-d04e-4299-9f37-778db7783971', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 47, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_bjpcFCcGSqvWHqfmTtxxfmFH', 'name': 'idzol cloud', 'latency': '275', 'health': 95, 'body': [{'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}], 'head': {'x': 7, 'y': 8}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_j4jWHwh67DQFKcMhgQKdt9S9', 'name': 'Eremetic Eric', 'latency': '27', 'health': 55, 'body': [{'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 7, 'y': 9}], 'head': {'x': 7, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_MVMHFFHPHbrwRdW3hyVqwJCd', 'name': 'Swiss Cheese', 'latency': '185', 'health': 99, 'body': [{'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 3, 'y': 6}, {'x': 2, 'y': 6}, {'x': 1, 'y': 6}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}], 'head': {'x': 5, 'y': 8}, 'length': 11, 'shout': '', 'squad': ''}, {'id': 'gs_yQ9cfVr6qdcQjFWFB6fJXbtc', 'name': 'BobFrit Jr', 'latency': '198', 'health': 63, 'body': [{'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}], 'head': {'x': 9, 'y': 4}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 4, 'y': 4}, {'x': 1, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_bjpcFCcGSqvWHqfmTtxxfmFH', 'name': 'idzol cloud', 'latency': '275', 'health': 95, 'body': [{'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}], 'head': {'x': 7, 'y': 8}, 'length': 8, 'shout': '', 'squad': ''}}],
    # [2,'', '', {}],
    # [3,'', '', {}],
    # [4,'', '', {}],
]



route_data = route_data_survive + route_data_attack

def printBoard(data):  
    w = int(data['board']['width'])
    h = int(data['board']['height'])
     
    # SNAKES 
    board = np.zeros((h, w), np.intc)
    snakes = data['board']['snakes']
    for snake in snakes:
        for pt in snake['body']:
            px = pt['x']
            py = pt['y']
            
            board[py, px] = CONST.legend['enemy-body']

        head = snake['head']
        px = head['x']
        py = head['y']
        board[py, px] = CONST.legend['enemy-head']

    you = data['you']
    for pt in you['body']:
        
        px = pt['x']
        py = pt['y']
        board[py, px] = CONST.legend['you-body']

    head = you['head']
    px = head['x']
    py = head['y']
    board[py, px] = CONST.legend['you-head']

    foods = data['board']['food']
    for food in foods:

        px = food['x']
        py = food['y']
        board[py, px] = CONST.legend['food']

    print(board)
    # return copy.copy(board)


total = len(route_data)
success = 0 
fail = 0 


for data in route_data:
    # Known dataset 
    silent = True
    response = handle_move(data[3], silent)
    if response["move"] == data[1]: 
        # Expected result
        # print("PASS. Went %s. Expected %s. Strategy: %s" % (str(response["move"]), data[1], data[2]))
        # printBoard(data[3])
        success += 1 

    else:
        print("FAIL. Went %s. Expected %s. Strategy: %s" % (str(response["move"]), data[1], data[2]))
        printBoard(data[3])
        # Replay move with debug on 
        # handle_move(data[3], False)
        fail += 1
        

print ("%d Test cases: %d Pass, %d Fail" % (total, success, fail))
    
