from server import handle_move

import numpy as np
# import copy as copy

import time as time
# from logClass import log

import constants as CONST
# import functions as fn

# from snakeClass import snake
# from boardClass import board

import cProfile, pstats
      

def printBoard(data):  
    w = int(data['board']['width'])
    h = int(data['board']['height'])
     
    # SNAKES 
    board = np.zeros((h, w), np.intc)
    snakes = data['board']['snakes']
    for snake in snakes:
        for pt in snake['body']:
            px = pt['x']
            py = pt['y']
            
            board[py, px] = CONST.legend['enemy-body']

        head = snake['head']
        px = head['x']
        py = head['y']
        board[py, px] = CONST.legend['enemy-head']

    you = data['you']
    for pt in you['body']:
        
        px = pt['x']
        py = pt['y']
        board[py, px] = CONST.legend['you-body']

    head = you['head']
    px = head['x']
    py = head['y']
    board[py, px] = CONST.legend['you-head']

    foods = data['board']['food']
    for food in foods:

        px = food['x']
        py = food['y']
        board[py, px] = CONST.legend['food']

    print(board)
    # return copy.copy(board)



route_survive = [
    [1, 'right','survive - chase tail instead of food',{'game': {'id': '8c202d0a-e493-4f3a-acc0-26b875d83c03', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 66, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_CytDcCKwYKvWQgcSjDbb7dG8', 'name': 'idzol cloud', 'latency': '240', 'health': 89, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 6}, {'x': 10, 'y': 5}, {'x': 10, 'y': 4}, {'x': 10, 'y': 3}], 'head': {'x': 6, 'y': 8}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_DGxwC3CFxH4jj4f6bhp7PVRD', 'name': 'vomc', 'latency': '181', 'health': 92, 'body': [{'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}], 'head': {'x': 4, 'y': 8}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_QGGGTBmP6phdFSB8CTpyjSt4', 'name': 'nates_python', 'latency': '182', 'health': 76, 'body': [{'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 7, 'y': 9}, {'x': 7, 'y': 10}, {'x': 8, 'y': 10}, {'x': 9, 'y': 10}, {'x': 10, 'y': 10}, {'x': 10, 'y': 9}, {'x': 9, 'y': 9}], 'head': {'x': 5, 'y': 9}, 'length': 9, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 2}, {'x': 5, 'y': 8}], 'hazards': []}, 'you': {'id': 'gs_CytDcCKwYKvWQgcSjDbb7dG8', 'name': 'idzol cloud', 'latency': '240', 'health': 89, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 6}, {'x': 10, 'y': 5}, {'x': 10, 'y': 4}, {'x': 10, 'y': 3}], 'head': {'x': 6, 'y': 8}, 'length': 12, 'shout': '', 'squad': ''}}],
    [12,'right', 'survive - see path through tail', {'game': {'id': '42bfec7b-2dc2-417a-af9d-a0c1f08cb323', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 191, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_fkHXpHg3QG6pJyjdBk9FWmRM', 'name': 'idzol cloud', 'latency': '206', 'health': 61, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 9, 'y': 2}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'head': {'x': 9, 'y': 10}, 'length': 22, 'shout': 'You are as a candle, the better burnt out.', 'squad': ''}, {'id': 'gs_b8CcJvjVWv3CvMwxXyt3dfKf', 'name': 'Jack of all Snakes', 'latency': '188', 'health': 84, 'body': [{'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 10, 'shout': '', 'squad': ''}], 'food': [{'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 6, 'y': 8}, {'x': 5, 'y': 3}], 'hazards': []}, 'you': {'id': 'gs_fkHXpHg3QG6pJyjdBk9FWmRM', 'name': 'idzol cloud', 'latency': '206', 'health': 61, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 8, 'y': 6}, {'x': 7, 'y': 6}, {'x': 6, 'y': 6}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 9, 'y': 2}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'head': {'x': 9, 'y': 10}, 'length': 22, 'shout': 'You are as a candle, the better burnt out.', 'squad': ''}}],
    
    [2, 'down', 'enemy strategy - one move to kill',{'game': {'id': 'd433023a-fb47-4fc3-9ec1-a30f694e4793', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 96, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_CCCpvxKBwPvRJM9G96dgXK3Q', 'name': 'idzol cloud', 'latency': '213', 'health': 73, 'body': [{'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}], 'head': {'x': 8, 'y': 2}, 'length': 9, 'shout': '', 'squad': ''}, {'id': 'gs_TDtcxGgVmxWmFvdhbySqwGfD', 'name': '>:3', 'latency': '402', 'health': 4, 'body': [{'x': 9, 'y': 1}, {'x': 9, 'y': 0}, {'x': 8, 'y': 0}], 'head': {'x': 9, 'y': 1}, 'length': 3, 'shout': '', 'squad': ''}, {'id': 'gs_KdSCHFc3pyhQ3PcYyXTWfpMY', 'name': 'Brainiac', 'latency': '255', 'health': 67, 'body': [{'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}], 'head': {'x': 2, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_8MRGqW6FmMKBQYfFcgqTH9pR', 'name': 'Super Snakey', 'latency': '206', 'health': 92, 'body': [{'x': 1, 'y': 3}, {'x': 1, 'y': 2}, {'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 7, 'y': 1}, {'x': 7, 'y': 2}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}], 'head': {'x': 1, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}], 'food': [{'x': 1, 'y': 9}, {'x': 4, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_CCCpvxKBwPvRJM9G96dgXK3Q', 'name': 'idzol cloud', 'latency': '213', 'health': 73, 'body': [{'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}], 'head': {'x': 8, 'y': 2}, 'length': 9, 'shout': '', 'squad': ''}}],
    [4, 'down', 'enemy strategy - two moves to kill', {'game': {'id': 'c105689d-eb47-4e18-ac97-ed6eb234969b', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 80, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_jCJpyKGpjvRVmQ7WYRRcgwkH', 'name': 'idzol cloud', 'latency': '218', 'health': 99, 'body': [{'x': 3, 'y': 9}, {'x': 3, 'y': 10}, {'x': 4, 'y': 10}, {'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}], 'head': {'x': 3, 'y': 9}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_CfjhM4RXS6KmGTjgtSbMqFR7', 'name': 'Swiss Cheese', 'latency': '180', 'health': 100, 'body': [{'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 8, 'y': 8}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 5, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_qg7DcGJ336mhwcGdRRPJHwTX', 'name': 'BobFrit Jr', 'latency': '196', 'health': 91, 'body': [{'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}], 'head': {'x': 2, 'y': 8}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 3, 'y': 5}, {'x': 5, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_jCJpyKGpjvRVmQ7WYRRcgwkH', 'name': 'idzol cloud', 'latency': '218', 'health': 99, 'body': [{'x': 3, 'y': 9}, {'x': 3, 'y': 10}, {'x': 4, 'y': 10}, {'x': 5, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}], 'head': {'x': 3, 'y': 9}, 'length': 13, 'shout': '', 'squad': ''}}],
    [5, 'up', 'enemy strategy - one move to kill', {'game': {'id': '61a48f68-8588-4994-a352-1df2021ad1e0', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 50, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_3CQG3SSptjCQTGGHkkBJMq7W', 'name': 'idzol cloud', 'latency': '225', 'health': 89, 'body': [{'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}], 'head': {'x': 10, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_t4KdPyYK6h8BP4wphwv3rRc7', 'name': 'icedostrich', 'latency': '101', 'health': 78, 'body': [{'x': 9, 'y': 1}, {'x': 9, 'y': 2}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}], 'head': {'x': 9, 'y': 1}, 'length': 7, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 1}, {'x': 10, 'y': 1}, {'x': 2, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_3CQG3SSptjCQTGGHkkBJMq7W', 'name': 'idzol cloud', 'latency': '225', 'health': 89, 'body': [{'x': 10, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}], 'head': {'x': 10, 'y': 4}, 'length': 8, 'shout': '', 'squad': ''}}],
    [6,'right', 'enemy strategy - two moves to kill', {'game': {'id': '1d057583-a2e7-4e97-ae8c-c33d8ee26433', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 121, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_FBjRfqRPG9DVcyWXjJ3MM799', 'name': 'idzol cloud', 'latency': '158', 'health': 90, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 13, 'shout': 'Thou hast no more brain than I have in mine elbows', 'squad': ''}, {'id': 'gs_YdQRfWGtbH7RqSVww8Hq9fVX', 'name': 'SnakeJS', 'latency': '174', 'health': 98, 'body': [{'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 6, 'y': 2}, {'x': 6, 'y': 1}, {'x': 5, 'y': 1}, {'x': 4, 'y': 1}, {'x': 3, 'y': 1}, {'x': 2, 'y': 1}, {'x': 1, 'y': 1}, {'x': 1, 'y': 2}, {'x': 0, 'y': 2}], 'head': {'x': 3, 'y': 8}, 'length': 18, 'shout': '[4 8] --> [3 10]', 'squad': ''}], 'food': [{'x': 7, 'y': 7}, {'x': 3, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_FBjRfqRPG9DVcyWXjJ3MM799', 'name': 'idzol cloud', 'latency': '158', 'health': 90, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 13, 'shout': 'Thou hast no more brain than I have in mine elbows', 'squad': ''}}],

    [7,'left', 'enemy intent - get food', {'game': {'id': '8ee4149a-7e3a-423f-b86f-96ef19bd4192', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 109, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_94jrfYxKtvV97bHfcDKWVTg3', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}, {'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 2, 'y': 0}, {'x': 1, 'y': 0}], 'head': {'x': 1, 'y': 10}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_krxgMMYGv6ggtvJKtcFwwktR', 'name': 'Blake', 'latency': '213', 'health': 91, 'body': [{'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 5, 'y': 2}, {'x': 6, 'y': 2}, {'x': 7, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}], 'head': {'x': 4, 'y': 7}, 'length': 14, 'shout': '', 'squad': ''}], 'food': [{'x': 4, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_94jrfYxKtvV97bHfcDKWVTg3', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}, {'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 2, 'y': 0}, {'x': 1, 'y': 0}], 'head': {'x': 1, 'y': 10}, 'length': 13, 'shout': '', 'squad': ''}}],
    
    [3, 'down', 'route selection - certain death vs possible death', {'game': {'id': '932cf8ae-de0c-4e63-a89d-7b259f886deb', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 143, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_DrdpjkdQSmFm6KGYwq7hJVHV', 'name': 'SnakeJS', 'latency': '192', 'health': 98, 'body': [{'x': 0, 'y': 7}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}], 'head': {'x': 0, 'y': 7}, 'length': 16, 'shout': '[1 7] --> [0 6]', 'squad': ''}], 'food': [{'x': 0, 'y': 6}, {'x': 1, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}}],
    [8,'up', 'enemy eating - certain death vs possible death ', {'game': {'id': '39f5f3fb-c456-4924-9abe-54117b608a12', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 32, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}, {'id': 'gs_CgyqbSwvKSphK6VRmHxrCWVW', 'name': 'moon-snake-pika', 'latency': '192', 'health': 89, 'body': [{'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 3, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}], 'head': {'x': 1, 'y': 7}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_B3hBgh8SfRXd9dtdff7CQT6F', 'name': 'starter_snake', 'latency': '235', 'health': 100, 'body': [{'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 4}], 'head': {'x': 0, 'y': 6}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}}],
    [9,'down', 'control area - safe board vs danger board', {'game': {'id': 'f76091b1-b5de-4e83-86b7-3119c9d76b0c', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 121, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_4kcXvqwTSKMRtH8MRPTdxSbK', 'name': 'idzol cloud', 'latency': '233', 'health': 100, 'body': [{'x': 10, 'y': 7}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 3, 'y': 3}], 'head': {'x': 10, 'y': 7}, 'length': 13, 'shout': 'Art thou a flesh-monger, a fool and a coward?', 'squad': ''}, {'id': 'gs_Ky9PfwF8CV6vVvKvSDJG8d46', 'name': 'CorneliusCodes', 'latency': '71', 'health': 93, 'body': [{'x': 5, 'y': 10}, {'x': 4, 'y': 10}, {'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}, {'x': 1, 'y': 7}], 'head': {'x': 5, 'y': 10}, 'length': 10, 'shout': '', 'squad': ''}], 'food': [{'x': 1, 'y': 1}, {'x': 2, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_4kcXvqwTSKMRtH8MRPTdxSbK', 'name': 'idzol cloud', 'latency': '233', 'health': 100, 'body': [{'x': 10, 'y': 7}, {'x': 9, 'y': 7}, {'x': 8, 'y': 7}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 3, 'y': 4}, {'x': 3, 'y': 3}, {'x': 3, 'y': 3}], 'head': {'x': 10, 'y': 7}, 'length': 13, 'shout': 'Art thou a flesh-monger, a fool and a coward?', 'squad': ''}}],

    [10,'right', 'enemy killcut - us eating and larger', {'game': {'id': 'dd09ebb2-bdeb-4b81-b76b-428817007c85', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 51, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_JR7C8rvVFfFydBH8XBhTQd9D', 'name': 'idzol cloud', 'latency': '237', 'health': 100, 'body': [{'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 7}], 'head': {'x': 7, 'y': 10}, 'length': 9, 'shout': 'Thou art as fat as butter', 'squad': ''}, {'id': 'gs_v7cWbF7WhCq6k8JmyMc6BXyB', 'name': 'Eve', 'latency': '182', 'health': 51, 'body': [{'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 0, 'y': 10}], 'head': {'x': 3, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_JTFWcPF4bw7DpW6f36pVDbqb', 'name': 'SnakeJS', 'latency': '181', 'health': 94, 'body': [{'x': 1, 'y': 4}, {'x': 0, 'y': 4}, {'x': 0, 'y': 5}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}], 'head': {'x': 1, 'y': 4}, 'length': 9, 'shout': '[0 4] --> [5 7]', 'squad': ''}], 'food': [{'x': 5, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_JR7C8rvVFfFydBH8XBhTQd9D', 'name': 'idzol cloud', 'latency': '237', 'health': 100, 'body': [{'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 7}], 'head': {'x': 7, 'y': 10}, 'length': 9, 'shout': 'Thou art as fat as butter', 'squad': ''}}],
    [11,'up', 'enemy killcut - ignore food and see danger', {'game': {'id': '2cad3115-593c-46a5-8165-841121466f24', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 92, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_VmWcGyCRgy44VRYgdccdY9KQ', 'name': 'idzol cloud', 'latency': '322', 'health': 100, 'body': [{'x': 0, 'y': 2}, {'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 2, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 7}], 'head': {'x': 0, 'y': 2}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_TPhGwH7RwCGCTX6fXPBgSwM7', 'name': 'Swiss Cheese', 'latency': '180', 'health': 78, 'body': [{'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}, {'x': 6, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}], 'head': {'x': 9, 'y': 3}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_7c3QYx43ycBdBJw9WV38XQxQ', 'name': 'Potoooooooo', 'latency': '2', 'health': 67, 'body': [{'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 7, 'y': 1}, {'x': 8, 'y': 1}], 'head': {'x': 5, 'y': 1}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 1}, {'x': 7, 'y': 7}, {'x': 3, 'y': 0}], 'hazards': []}, 'you': {'id': 'gs_VmWcGyCRgy44VRYgdccdY9KQ', 'name': 'idzol cloud', 'latency': '322', 'health': 100, 'body': [{'x': 0, 'y': 2}, {'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}, {'x': 2, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 7}], 'head': {'x': 0, 'y': 2}, 'length': 12, 'shout': '', 'squad': ''}}],
    [14,'up', 'enemy killcut - 100 percent chance to kill', {'game': {'id': '3b7a1097-2e87-4515-973a-43b68843da01', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 104, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_hyhjDjFpSySxTGXRGc8yvDC8', 'name': 'GGGelo', 'latency': '209', 'health': 90, 'body': [{'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}, {'x': 5, 'y': 7}], 'head': {'x': 9, 'y': 5}, 'length': 11, 'shout': "It'ssss over my friend", 'squad': ''}, {'id': 'gs_w4HMHv8GSbhjhVDg3BWRhd9C', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 3, 'y': 2}, {'x': 2, 'y': 2}, {'x': 1, 'y': 2}, {'x': 1, 'y': 3}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}], 'head': {'x': 10, 'y': 2}, 'length': 13, 'shout': '', 'squad': ''}], 'food': [{'x': 10, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_w4HMHv8GSbhjhVDg3BWRhd9C', 'name': 'idzol cloud', 'latency': '221', 'health': 99, 'body': [{'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 3, 'y': 2}, {'x': 2, 'y': 2}, {'x': 1, 'y': 2}, {'x': 1, 'y': 3}, {'x': 1, 'y': 4}, {'x': 1, 'y': 5}], 'head': {'x': 10, 'y': 2}, 'length': 13, 'shout': '', 'squad': ''}}],

    [13,'left', 'control area - safe board vs danger board', {'game': {'id': 'b3b743ef-6e91-489d-8e3a-89221897a54f', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 141, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_XCYgxFhjV4yKvyrH6tJYj4p4', 'name': 'idzol cloud', 'latency': '207', 'health': 86, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 3, 'y': 10}, 'length': 14, 'shout': 'Thou elvish-mark’d, abortive, rooting hog!', 'squad': ''}, {'id': 'gs_M7kmgFmhr8wG8jQrhphSpW4X', 'name': 'soba', 'latency': '47', 'health': 87, 'body': [{'x': 2, 'y': 7}, {'x': 3, 'y': 7}, {'x': 4, 'y': 7}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 5, 'y': 4}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}, {'x': 8, 'y': 3}, {'x': 8, 'y': 2}, {'x': 8, 'y': 1}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 6, 'y': 0}, {'x': 5, 'y': 0}], 'head': {'x': 2, 'y': 7}, 'length': 17, 'shout': 'chasing snack', 'squad': ''}], 'food': [{'x': 0, 'y': 9}, {'x': 3, 'y': 2}, {'x': 2, 'y': 10}, {'x': 10, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_XCYgxFhjV4yKvyrH6tJYj4p4', 'name': 'idzol cloud', 'latency': '207', 'health': 86, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 3, 'y': 10}, 'length': 14, 'shout': 'Thou elvish-mark’d, abortive, rooting hog!', 'squad': ''}}],
    [15,'down', 'enemy threat - choose safer options', {'game': {'id': '611870be-9cf5-420a-a487-0706367e1182', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 69, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_vK3q7dR7JFT7SGkpMmXBfrGV', 'name': 'idzol cloud', 'latency': '295', 'health': 73, 'body': [{'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 4, 'y': 3}, {'x': 4, 'y': 4}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 5, 'y': 2}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_X4fKXrfPgxjwB9XxRQyDdbFH', 'name': 'Wormius', 'latency': '184', 'health': 97, 'body': [{'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 8, 'y': 3}, {'x': 8, 'y': 2}, {'x': 8, 'y': 1}, {'x': 8, 'y': 0}, {'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 6, 'y': 5}], 'head': {'x': 7, 'y': 4}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_kthDD4pjQv3T9W8kjrFV9VjJ', 'name': 'Eve', 'latency': '191', 'health': 33, 'body': [{'x': 7, 'y': 10}, {'x': 8, 'y': 10}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}], 'head': {'x': 7, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_8C9wmGCKmYbRqStFMFjj4GQS', 'name': 'Killer whale', 'latency': '10', 'health': 98, 'body': [{'x': 1, 'y': 2}, {'x': 2, 'y': 2}, {'x': 3, 'y': 2}, {'x': 3, 'y': 3}, {'x': 3, 'y': 4}], 'head': {'x': 1, 'y': 2}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_vK3q7dR7JFT7SGkpMmXBfrGV', 'name': 'idzol cloud', 'latency': '295', 'health': 73, 'body': [{'x': 5, 'y': 2}, {'x': 4, 'y': 2}, {'x': 4, 'y': 3}, {'x': 4, 'y': 4}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 5, 'y': 2}, 'length': 7, 'shout': '', 'squad': ''}}],
    [16,'right', 'enemy predict - wall danger. deadend in three moves', {'game': {'id': 'b88daa36-260b-4e28-9f14-62feafcb4081', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 346, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_cwXdP7xfX6chdvKCM4g7gX6B', 'name': 'Killer whale', 'latency': '3', 'health': 92, 'body': [{'x': 1, 'y': 7}, {'x': 1, 'y': 6}, {'x': 2, 'y': 6}, {'x': 2, 'y': 7}, {'x': 2, 'y': 8}, {'x': 2, 'y': 9}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 5, 'y': 8}, {'x': 6, 'y': 8}, {'x': 7, 'y': 8}, {'x': 7, 'y': 7}, {'x': 7, 'y': 6}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}, {'x': 7, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 1}, {'x': 8, 'y': 0}], 'head': {'x': 1, 'y': 7}, 'length': 21, 'shout': '', 'squad': ''}, {'id': 'gs_DFbR47pJtMTS86bpFxPxhVbK', 'name': 'idzol cloud', 'latency': '256', 'health': 86, 'body': [{'x': 1, 'y': 5}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 1, 'y': 2}, {'x': 1, 'y': 1}, {'x': 1, 'y': 0}, {'x': 2, 'y': 0}, {'x': 2, 'y': 1}, {'x': 2, 'y': 2}, {'x': 2, 'y': 3}, {'x': 3, 'y': 3}, {'x': 3, 'y': 2}, {'x': 3, 'y': 1}, {'x': 3, 'y': 0}, {'x': 4, 'y': 0}, {'x': 4, 'y': 1}, {'x': 4, 'y': 2}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 2}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}], 'head': {'x': 1, 'y': 5}, 'length': 28, 'shout': '', 'squad': ''}], 'food': [{'x': 10, 'y': 0}, {'x': 8, 'y': 10}, {'x': 5, 'y': 10}, {'x': 10, 'y': 9}, {'x': 8, 'y': 4}, {'x': 9, 'y': 9}, {'x': 10, 'y': 10}, {'x': 3, 'y': 10}, {'x': 6, 'y': 7}, {'x': 4, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_DFbR47pJtMTS86bpFxPxhVbK', 'name': 'idzol cloud', 'latency': '256', 'health': 86, 'body': [{'x': 1, 'y': 5}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 1, 'y': 2}, {'x': 1, 'y': 1}, {'x': 1, 'y': 0}, {'x': 2, 'y': 0}, {'x': 2, 'y': 1}, {'x': 2, 'y': 2}, {'x': 2, 'y': 3}, {'x': 3, 'y': 3}, {'x': 3, 'y': 2}, {'x': 3, 'y': 1}, {'x': 3, 'y': 0}, {'x': 4, 'y': 0}, {'x': 4, 'y': 1}, {'x': 4, 'y': 2}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 2}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}], 'head': {'x': 1, 'y': 5}, 'length': 28, 'shout': '', 'squad': ''}}],
    [17, 'left', 'enemy threat - avoid larger snake', {'game': {'id': 'e3ee6d39-510e-4fa9-8f06-f161249347bb', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 62, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_wTRG837kkp9gcmYbxjJ84QdY', 'name': 'Ophion', 'latency': '74', 'health': 95, 'body': [{'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 6}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 6, 'y': 7}], 'head': {'x': 3, 'y': 9}, 'length': 10, 'shout': '', 'squad': ''}, {'id': 'gs_78fYgc9xqQTX9CpFcgYhhJY3', 'name': '^SandySnek^', 'latency': '251', 'health': 90, 'body': [{'x': 1, 'y': 3}, {'x': 1, 'y': 2}, {'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 3, 'y': 2}], 'head': {'x': 1, 'y': 3}, 'length': 6, 'shout': '', 'squad': ''}, {'id': 'gs_6D9DgjVthXBmCQtWFpgcPDmb', 'name': 'Idzol', 'latency': '323', 'health': 93, 'body': [{'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}], 'head': {'x': 2, 'y': 10}, 'length': 8, 'shout': '', 'squad': ''}], 'food': [{'x': 10, 'y': 1}, {'x': 5, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_6D9DgjVthXBmCQtWFpgcPDmb', 'name': 'Idzol', 'latency': '323', 'health': 93, 'body': [{'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 2, 'y': 3}], 'head': {'x': 2, 'y': 10}, 'length': 8, 'shout': '', 'squad': ''}}],
    [18, 'up', 'enemy threat - avoid larger snake. two moves', {'game': {'id': 'f1413ec5-649a-406e-a5ef-0384de513600', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 42, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_S6v9RrmXCcBC9ddCKpqct47D', 'name': 'king clu-less', 'latency': '196', 'health': 72, 'body': [{'x': 4, 'y': 8}, {'x': 5, 'y': 8}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 5, 'y': 7}], 'head': {'x': 4, 'y': 8}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_PCMVFT8C3RpGqwjcxjbtHp8Y', 'name': 'Idzol', 'latency': '220', 'health': 97, 'body': [{'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 9, 'y': 9}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}], 'head': {'x': 7, 'y': 9}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_ptXF8jW3PpTSJGdWFT8fmJTB', 'name': 'Piggy', 'latency': '173', 'health': 58, 'body': [{'x': 5, 'y': 3}, {'x': 6, 'y': 3}, {'x': 7, 'y': 3}], 'head': {'x': 5, 'y': 3}, 'length': 3, 'shout': '', 'squad': ''}, {'id': 'gs_KyPt6DgMr8pg4V9d4wVChxVW', 'name': 'LaChangaNeta', 'latency': '247', 'health': 98, 'body': [{'x': 4, 'y': 10}, {'x': 3, 'y': 10}, {'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 6}], 'head': {'x': 4, 'y': 10}, 'length': 8, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 2}], 'hazards': []}, 'you': {'id': 'gs_PCMVFT8C3RpGqwjcxjbtHp8Y', 'name': 'Idzol', 'latency': '220', 'health': 97, 'body': [{'x': 7, 'y': 9}, {'x': 7, 'y': 8}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 9, 'y': 9}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}], 'head': {'x': 7, 'y': 9}, 'length': 7, 'shout': '', 'squad': ''}}],
   

    [18, 'down|left', 'enemy threat - same length. draw chance', {'game': {'id': '08ea3e7d-61d9-4514-bb1b-cf9a0423da44', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 15, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_pwcwmtYqH8vX63wVSJp7b7Kc', 'name': 'slinky', 'latency': '25', 'health': 100, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 5}], 'head': {'x': 9, 'y': 10}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_ktFRGJQSCfwS6hp87jTTyqVF', 'name': "Flo's Snake", 'latency': '176', 'health': 89, 'body': [{'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 8, 'y': 7}, {'x': 8, 'y': 6}], 'head': {'x': 6, 'y': 7}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_BxPkSDS9gp99k86QdbJK74mW', 'name': 'Idzol', 'latency': '247', 'health': 87, 'body': [{'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 6, 'y': 4}], 'head': {'x': 6, 'y': 5}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_g4gVCgF8VGCK9WB8pwBd8drX', 'name': 'Dipstick', 'latency': '197', 'health': 91, 'body': [{'x': 3, 'y': 6}, {'x': 3, 'y': 5}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}, {'x': 4, 'y': 5}], 'head': {'x': 3, 'y': 6}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 3}], 'hazards': []}, 'you': {'id': 'gs_BxPkSDS9gp99k86QdbJK74mW', 'name': 'Idzol', 'latency': '247', 'health': 87, 'body': [{'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 6, 'y': 4}], 'head': {'x': 6, 'y': 5}, 'length': 4, 'shout': '', 'squad': ''}}],
    
    [17, 'right', 'enemy threat - food one away and larger', {'game': {'id': '27d52850-a9fd-4648-967e-e950369a82d4', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'custom'}, 'turn': 27, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_T6bghcvydvmbXC33VjCSWq8Q', 'name': 'Idzol', 'latency': '177', 'health': 99, 'body': [{'x': 8, 'y': 9}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 5, 'y': 10}, {'x': 4, 'y': 10}, {'x': 4, 'y': 9}], 'head': {'x': 8, 'y': 9}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_9HvXMbk3xmx6WXKkMmpQHhp9', 'name': 'idzol cloud dev', 'latency': '230', 'health': 99, 'body': [{'x': 7, 'y': 8}, {'x': 7, 'y': 7}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 5, 'y': 6}, {'x': 4, 'y': 6}, {'x': 3, 'y': 6}, {'x': 2, 'y': 6}], 'head': {'x': 7, 'y': 8}, 'length': 8, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 8}, {'x': 4, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_T6bghcvydvmbXC33VjCSWq8Q', 'name': 'Idzol', 'latency': '177', 'health': 99, 'body': [{'x': 8, 'y': 9}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 5, 'y': 10}, {'x': 4, 'y': 10}, {'x': 4, 'y': 9}], 'head': {'x': 8, 'y': 9}, 'length': 7, 'shout': '', 'squad': ''}}],
    [19, 'right', 'enemy threat - food one away and larger', {'game': {'id': '8d35a6bd-44a2-435f-88f7-0a27379c68b9', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 60, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_fxTWBRcCwKB7Gy3vHgKXr39D', 'name': 'Ava', 'latency': '23', 'health': 94, 'body': [{'x': 3, 'y': 7}, {'x': 3, 'y': 8}, {'x': 2, 'y': 8}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 1, 'y': 9}, {'x': 1, 'y': 8}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}], 'head': {'x': 3, 'y': 7}, 'length': 13, 'shout': '', 'squad': ''}, {'id': 'gs_Q6gbG3GqGTmFMGvyqRTDjjHV', 'name': 'king clu-less', 'latency': '186', 'health': 91, 'body': [{'x': 7, 'y': 3}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 8, 'y': 4}], 'head': {'x': 7, 'y': 3}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_RdDKvCcqSkrWVjq7KDymVQkF', 'name': 'SnakeDrop', 'latency': '83', 'health': 99, 'body': [{'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}, {'x': 5, 'y': 1}, {'x': 6, 'y': 1}, {'x': 7, 'y': 1}], 'head': {'x': 2, 'y': 2}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_pY8KHRhfhcQ7bvXgb44q4JXM', 'name': 'Idzol', 'latency': '258', 'health': 84, 'body': [{'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}], 'head': {'x': 4, 'y': 6}, 'length': 6, 'shout': '', 'squad': ''}], 'food': [{'x': 4, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_pY8KHRhfhcQ7bvXgb44q4JXM', 'name': 'Idzol', 'latency': '258', 'health': 84, 'body': [{'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 5, 'y': 3}, {'x': 5, 'y': 4}], 'head': {'x': 4, 'y': 6}, 'length': 6, 'shout': '', 'squad': ''}}],

    # [2,'', '', {}],
    # [2,'', '', {}],
    # [2,'', '', {}],
    # [2,'', '', {}],
    # [2,'', '', {}],   
]

route_attack = [
    [101,'up', 'headon collision - ignore tail and smaller', {'game': {'id': '6871f4f4-d04e-4299-9f37-778db7783971', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 47, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_bjpcFCcGSqvWHqfmTtxxfmFH', 'name': 'idzol cloud', 'latency': '275', 'health': 95, 'body': [{'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}], 'head': {'x': 7, 'y': 8}, 'length': 8, 'shout': '', 'squad': ''}, {'id': 'gs_j4jWHwh67DQFKcMhgQKdt9S9', 'name': 'Eremetic Eric', 'latency': '27', 'health': 55, 'body': [{'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 7, 'y': 9}], 'head': {'x': 7, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_MVMHFFHPHbrwRdW3hyVqwJCd', 'name': 'Swiss Cheese', 'latency': '185', 'health': 99, 'body': [{'x': 5, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 7}, {'x': 4, 'y': 6}, {'x': 3, 'y': 6}, {'x': 2, 'y': 6}, {'x': 1, 'y': 6}, {'x': 0, 'y': 6}, {'x': 0, 'y': 7}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}], 'head': {'x': 5, 'y': 8}, 'length': 11, 'shout': '', 'squad': ''}, {'id': 'gs_yQ9cfVr6qdcQjFWFB6fJXbtc', 'name': 'BobFrit Jr', 'latency': '198', 'health': 63, 'body': [{'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}], 'head': {'x': 9, 'y': 4}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 4, 'y': 4}, {'x': 1, 'y': 5}], 'hazards': []}, 'you': {'id': 'gs_bjpcFCcGSqvWHqfmTtxxfmFH', 'name': 'idzol cloud', 'latency': '275', 'health': 95, 'body': [{'x': 7, 'y': 8}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}], 'head': {'x': 7, 'y': 8}, 'length': 8, 'shout': '', 'squad': ''}}],
    # [2,'', '', {}],
    # [3,'', '', {}],
    # [4,'', '', {}],
]

route_general = [
    [201,'right', 'routing - find larger space', {'game': {'id': '1ac6a157-8ebe-41bd-8b55-cc849fa9aa4e', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 150, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_XbyWGwCdwSp9S8jmwhGfGYfX', 'name': 'UNI', 'latency': '342', 'health': 51, 'body': [{'x': 1, 'y': 1}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 3, 'y': 0}, {'x': 4, 'y': 0}, {'x': 5, 'y': 0}], 'head': {'x': 1, 'y': 1}, 'length': 6, 'shout': '357', 'squad': ''}, {'id': 'gs_KgDfdjw9pSQpHXwPGyxRgG7P', 'name': 'Killer whale', 'latency': '2', 'health': 88, 'body': [{'x': 0, 'y': 8}, {'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 1, 'y': 8}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 1, 'y': 6}, {'x': 1, 'y': 5}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 1, 'y': 2}], 'head': {'x': 0, 'y': 8}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_dXjRmTTjWPGXCGXPX4pkH8WM', 'name': 'idzol cloud', 'latency': '184', 'health': 96, 'body': [{'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 5, 'y': 10}], 'head': {'x': 2, 'y': 10}, 'length': 22, 'shout': '', 'squad': ''}], 'food': [{'x': 9, 'y': 3}, {'x': 5, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_dXjRmTTjWPGXCGXPX4pkH8WM', 'name': 'idzol cloud', 'latency': '184', 'health': 96, 'body': [{'x': 2, 'y': 10}, {'x': 2, 'y': 9}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 5, 'y': 10}], 'head': {'x': 2, 'y': 10}, 'length': 22, 'shout': '', 'squad': ''}}],
    [202,'down', 'routing - avoid deadend. no threats', {'game': {'id': 'b1b5fb81-3287-41ac-98e8-d40a59b306d3', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 41, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_FvTBBqJMkQ6CM68DGmyWkydC', 'name': 'FirstCollabSnake', 'latency': '204', 'health': 94, 'body': [{'x': 3, 'y': 4}, {'x': 3, 'y': 5}, {'x': 3, 'y': 6}, {'x': 3, 'y': 7}, {'x': 3, 'y': 8}, {'x': 4, 'y': 8}, {'x': 4, 'y': 7}], 'head': {'x': 3, 'y': 4}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_DGYfRypdK7fdF9kPrrcStvv9', 'name': 'Idzol', 'latency': '207', 'health': 97, 'body': [{'x': 10, 'y': 5}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 10, 'y': 5}, 'length': 9, 'shout': 'Go, prick thy face, and over-red thy fear, Thou lily-liver’d boy', 'squad': ''}, {'id': 'gs_PWMMHVJB9ckKFhHyw4GDh4yb', 'name': 'Lethal Line', 'latency': '312', 'health': 78, 'body': [{'x': 7, 'y': 2}, {'x': 7, 'y': 3}, {'x': 7, 'y': 4}, {'x': 7, 'y': 5}], 'head': {'x': 7, 'y': 2}, 'length': 4, 'shout': 'By the power of coffee!', 'squad': ''}, {'id': 'gs_Gr9yCxkc7HbSwgpmS7WpxPMQ', 'name': 'Legless Lizard', 'latency': '65', 'health': 93, 'body': [{'x': 2, 'y': 3}, {'x': 2, 'y': 4}, {'x': 2, 'y': 5}, {'x': 2, 'y': 6}, {'x': 2, 'y': 7}], 'head': {'x': 2, 'y': 3}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 2, 'y': 10}, {'x': 7, 'y': 1}, {'x': 5, 'y': 1}, {'x': 2, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_DGYfRypdK7fdF9kPrrcStvv9', 'name': 'Idzol', 'latency': '207', 'health': 97, 'body': [{'x': 10, 'y': 5}, {'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 10, 'y': 5}, 'length': 9, 'shout': 'Go, prick thy face, and over-red thy fear, Thou lily-liver’d boy', 'squad': ''}}],

    [203,'left|right', 'routing - avoid enemy when eating food', {'game': {'id': '538d7ded-94b5-4cf6-84ea-80db546c7ad9', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 32, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_yDBc7vMtgtkd3KbtdVtKwpKR', 'name': 'Idzol', 'latency': '204', 'health': 78, 'body': [{'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}, {'x': 9, 'y': 9}], 'head': {'x': 9, 'y': 5}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_rCrwWxRfgWB9TyDb7bDxDQtP', 'name': 'SnakeJS', 'latency': '180', 'health': 100, 'body': [{'x': 8, 'y': 0}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 9, 'y': 4}, {'x': 9, 'y': 4}], 'head': {'x': 8, 'y': 0}, 'length': 7, 'shout': 'ATE_FOOD [8 1] --> [8 0]', 'squad': ''}, {'id': 'gs_8qkV8Tjh7dmYHTf7kQX6tjd6', 'name': 'a noodle full of danger', 'latency': '29', 'health': 81, 'body': [{'x': 4, 'y': 6}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 4}, {'x': 5, 'y': 3}, {'x': 4, 'y': 3}], 'head': {'x': 4, 'y': 6}, 'length': 6, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 10}], 'hazards': []}, 'you': {'id': 'gs_yDBc7vMtgtkd3KbtdVtKwpKR', 'name': 'Idzol', 'latency': '204', 'health': 78, 'body': [{'x': 9, 'y': 5}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}, {'x': 9, 'y': 9}], 'head': {'x': 9, 'y': 5}, 'length': 5, 'shout': '', 'squad': ''}}],

    [205,'left', 'routing - avoid deadend. no threats', {'game': {'id': '78a0e4e0-7ade-4d3f-a909-ca51148a1138', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 126, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_XFq4BSXmWx4xyqGKSjQ8WSrG', 'name': 'Pixel', 'latency': '67', 'health': 11, 'body': [{'x': 1, 'y': 1}, {'x': 0, 'y': 1}, {'x': 0, 'y': 0}, {'x': 1, 'y': 0}, {'x': 2, 'y': 0}], 'head': {'x': 1, 'y': 1}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_Vd48wprxm9GC8CW9WXRbySMV', 'name': 'Idzol', 'latency': '163', 'health': 97, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 7, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 10}, {'x': 7, 'y': 10}, {'x': 8, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 6, 'y': 8}, 'length': 16, 'shout': '', 'squad': ''}, {'id': 'gs_qhC47YjDYd6fHWMbygHxV94K', 'name': 'battlesnak', 'latency': '171', 'health': 99, 'body': [{'x': 7, 'y': 1}, {'x': 8, 'y': 1}, {'x': 8, 'y': 2}, {'x': 9, 'y': 2}, {'x': 9, 'y': 1}, {'x': 10, 'y': 1}, {'x': 10, 'y': 2}], 'head': {'x': 7, 'y': 1}, 'length': 7, 'shout': '', 'squad': ''}], 'food': [{'x': 1, 'y': 9}, {'x': 7, 'y': 2}, {'x': 10, 'y': 4}, {'x': 6, 'y': 0}], 'hazards': []}, 'you': {'id': 'gs_Vd48wprxm9GC8CW9WXRbySMV', 'name': 'Idzol', 'latency': '163', 'health': 97, 'body': [{'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 8, 'y': 5}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 7, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 10}, {'x': 7, 'y': 10}, {'x': 8, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 6, 'y': 8}, 'length': 16, 'shout': '', 'squad': ''}}],
    [206,'right', 'routing - avoid tail loop, food interrupt', {'game': {'id': '5a017f70-4faf-4640-a06e-d08ceac0966d', 'timeout': 500, 'ruleset': {'name': 'solo', 'version': 'cli'}}, 'turn': 339, 'board': {'height': 11, 'width': 11, 'food': [{'x': 10, 'y': 3}, {'x': 2, 'y': 0}, {'x': 10, 'y': 10}, {'x': 10, 'y': 0}, {'x': 10, 'y': 9}, {'x': 10, 'y': 8}, {'x': 3, 'y': 1}, {'x': 4, 'y': 10}, {'x': 0, 'y': 5}, {'x': 1, 'y': 2}, {'x': 0, 'y': 1}, {'x': 0, 'y': 6}, {'x': 0, 'y': 2}, {'x': 1, 'y': 1}, {'x': 3, 'y': 8}, {'x': 8, 'y': 0}, {'x': 4, 'y': 1}, {'x': 1, 'y': 3}, {'x': 1, 'y': 10}, {'x': 3, 'y': 3}, {'x': 3, 'y': 6}, {'x': 4, 'y': 0}, {'x': 10, 'y': 5}, {'x': 7, 'y': 0}, {'x': 5, 'y': 9}], 'hazards': [], 'snakes': [{'id': 'a4450744-eda4-47a3-b5d9-b785e9ad051f', 'name': 'idzol', 'health': 2, 'body': [{'x': 9, 'y': 9}, {'x': 9, 'y': 10}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}], 'latency': '0', 'head': {'x': 9, 'y': 9}, 'length': 24, 'shout': '', 'squad': ''}]}, 'you': {'id': 'a4450744-eda4-47a3-b5d9-b785e9ad051f', 'name': 'idzol', 'health': 2, 'body': [{'x': 9, 'y': 9}, {'x': 9, 'y': 10}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 6, 'y': 10}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 5, 'y': 8}, {'x': 5, 'y': 7}, {'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 6, 'y': 5}, {'x': 7, 'y': 5}, {'x': 7, 'y': 6}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}, {'x': 8, 'y': 9}, {'x': 8, 'y': 8}, {'x': 8, 'y': 7}, {'x': 8, 'y': 6}, {'x': 9, 'y': 6}, {'x': 9, 'y': 7}, {'x': 9, 'y': 8}], 'latency': '0', 'head': {'x': 9, 'y': 9}, 'length': 24, 'shout': '', 'squad': ''}}],
    [209, 'up|right', 'routing - tail avoidance after eating', {'game': {'id': '037800b2-ca3c-47e7-b06b-218479f736fd', 'timeout': 500, 'ruleset': {'name': 'solo', 'version': 'cli'}}, 'turn': 52, 'board': {'height': 11, 'width': 11, 'food': [{'x': 4, 'y': 2}, {'x': 2, 'y': 1}, {'x': 6, 'y': 1}, {'x': 1, 'y': 4}, {'x': 3, 'y': 9}, {'x': 8, 'y': 8}, {'x': 1, 'y': 2}, {'x': 1, 'y': 9}], 'hazards': [], 'snakes': [{'id': '1a66e369-9dab-4be6-a5f1-14be2207ef73', 'name': 'idzol', 'health': 100, 'body': [{'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}, {'x': 5, 'y': 7}, {'x': 5, 'y': 7}], 'latency': '0', 'head': {'x': 6, 'y': 7}, 'length': 7, 'shout': '', 'squad': ''}]}, 'you': {'id': '1a66e369-9dab-4be6-a5f1-14be2207ef73', 'name': 'idzol', 'health': 100, 'body': [{'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}, {'x': 5, 'y': 7}, {'x': 5, 'y': 7}], 'latency': '0', 'head': {'x': 6, 'y': 7}, 'length': 7, 'shout': '', 'squad': ''}}],

    [207,'down|left', 'routing - self collision avoidance. tail', {'game': {'id': 'f2293c7c-8fc1-4031-9de7-03ef643db167', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 64, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_cQGVkyS4VDcK9t47BjTbyPt3', 'name': 'Idzol', 'latency': '210', 'health': 89, 'body': [{'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 6, 'y': 6}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 6}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}], 'head': {'x': 6, 'y': 4}, 'length': 9, 'shout': '', 'squad': ''}, {'id': 'gs_qTS8hHQ7R7KWxcWpQgRhXc3H', 'name': 'Van Hohenheim', 'latency': '215', 'health': 38, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 2, 'y': 4}, {'x': 1, 'y': 4}], 'head': {'x': 1, 'y': 5}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 6, 'y': 9}], 'hazards': []}, 'you': {'id': 'gs_cQGVkyS4VDcK9t47BjTbyPt3', 'name': 'Idzol', 'latency': '210', 'health': 89, 'body': [{'x': 6, 'y': 4}, {'x': 6, 'y': 5}, {'x': 6, 'y': 6}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 6}, {'x': 7, 'y': 5}, {'x': 7, 'y': 4}, {'x': 7, 'y': 3}], 'head': {'x': 6, 'y': 4}, 'length': 9, 'shout': '', 'squad': ''}}],
    [208,'left|right', 'routing - wall avoidance', {'game': {'id': '7a3db0cc-6863-4013-929d-db3513600103', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 9, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_jWSkBKRfRQhhkvcprK9wGWJV', 'name': 'Idzol', 'latency': '265', 'health': 93, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 3, 'y': 9}], 'head': {'x': 5, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_BRSvcdJP9hjWrkmVB8HTRyG4', 'name': 'Prometheus', 'latency': '179', 'health': 91, 'body': [{'x': 9, 'y': 10}, {'x': 9, 'y': 9}, {'x': 10, 'y': 9}], 'head': {'x': 9, 'y': 10}, 'length': 3, 'shout': '', 'squad': ''}, {'id': 'gs_8JhhSyRWFPf4MvQvwrfK6CbK', 'name': 'kaa', 'latency': '313', 'health': 99, 'body': [{'x': 6, 'y': 3}, {'x': 6, 'y': 2}, {'x': 5, 'y': 2}, {'x': 5, 'y': 1}], 'head': {'x': 6, 'y': 3}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_R9fFCkBR7C3FmTjKKY9HHDMC', 'name': 'biter', 'latency': '22', 'health': 99, 'body': [{'x': 5, 'y': 6}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}], 'head': {'x': 5, 'y': 6}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 6}], 'hazards': []}, 'you': {'id': 'gs_jWSkBKRfRQhhkvcprK9wGWJV', 'name': 'Idzol', 'latency': '265', 'health': 93, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 3, 'y': 9}], 'head': {'x': 5, 'y': 10}, 'length': 4, 'shout': '', 'squad': ''}}],

    [204,'down|left', 'routing - chase food, not chase tail', {'game': {'id': 'dd829ac3-000b-4874-aa3d-ba046f2c8d7b', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 18, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_mhhK8xHgFddP3cqwgPjrYtfT', 'name': 'hhhotdaysssnake', 'latency': '80', 'health': 88, 'body': [{'x': 2, 'y': 10}, {'x': 1, 'y': 10}, {'x': 0, 'y': 10}, {'x': 0, 'y': 9}], 'head': {'x': 2, 'y': 10}, 'length': 4, 'shout': 'Make it', 'squad': ''}, {'id': 'gs_fQx7Dg8pQY697gx9SPH6KpYM', 'name': 'Idzol', 'latency': '189', 'health': 84, 'body': [{'x': 9, 'y': 9}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 9, 'y': 9}, 'length': 4, 'shout': '', 'squad': ''}, {'id': 'gs_Kfy7PR69GJJQRCxhFbS9vyrD', 'name': 'Milktea', 'latency': '219', 'health': 94, 'body': [{'x': 1, 'y': 5}, {'x': 1, 'y': 4}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 3, 'y': 3}], 'head': {'x': 1, 'y': 5}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_4k667Wy3F8JdQHMRVkGHGvr3', 'name': 'battlesnak', 'latency': '175', 'health': 98, 'body': [{'x': 6, 'y': 4}, {'x': 5, 'y': 4}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}], 'head': {'x': 6, 'y': 4}, 'length': 6, 'shout': '', 'squad': ''}], 'food': [{'x': 7, 'y': 3}], 'hazards': []}, 'you': {'id': 'gs_fQx7Dg8pQY697gx9SPH6KpYM', 'name': 'Idzol', 'latency': '189', 'health': 84, 'body': [{'x': 9, 'y': 9}, {'x': 10, 'y': 9}, {'x': 10, 'y': 10}, {'x': 9, 'y': 10}], 'head': {'x': 9, 'y': 9}, 'length': 4, 'shout': '', 'squad': ''}}],

    [210, 'right', 'routing - large cavern detection', {'game': {'id': '428b6b8d-6b77-4ef7-9062-4f757157d22d', 'timeout': 500, 'ruleset': {'name': 'solo', 'version': 'cli'}}, 'turn': 282, 'board': {'height': 11, 'width': 11, 'food': [{'x': 1, 'y': 10}, {'x': 9, 'y': 7}, {'x': 0, 'y': 1}, {'x': 8, 'y': 2}, {'x': 9, 'y': 6}], 'hazards': [], 'snakes': [{'id': '7ac156d6-2dc2-4761-988a-6be8e997b772', 'name': 'idzol', 'health': 99, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 8}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 0, 'y': 3}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 4, 'y': 0}, {'x': 5, 'y': 0}, {'x': 6, 'y': 0}, {'x': 7, 'y': 0}, {'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 0}, {'x': 10, 'y': 1}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'latency': '0', 'head': {'x': 5, 'y': 10}, 'length': 40, 'shout': '', 'squad': ''}]}, 'you': {'id': '7ac156d6-2dc2-4761-988a-6be8e997b772', 'name': 'idzol', 'health': 99, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 8}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 0, 'y': 3}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 4, 'y': 0}, {'x': 5, 'y': 0}, {'x': 6, 'y': 0}, {'x': 7, 'y': 0}, {'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 0}, {'x': 10, 'y': 1}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'latency': '0', 'head': {'x': 5, 'y': 10}, 'length': 40, 'shout': '', 'squad': ''}}],
    [211, 'right', 'routing - medium cavern detection ', {'game': {'id': 'f45530a5-ad8d-406a-945f-141603ae4e3d', 'timeout': 500, 'ruleset': {'name': 'solo', 'version': 'cli'}}, 'turn': 162, 'board': {'height': 11, 'width': 11, 'food': [{'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 2}, {'x': 4, 'y': 5}, {'x': 2, 'y': 0}, {'x': 3, 'y': 6}, {'x': 0, 'y': 7}], 'hazards': [], 'snakes': [{'id': '4bf12628-6a21-49f1-aa52-0e0a1a56fe47', 'name': 'idzol', 'health': 100, 'body': [{'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 7, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 10, 'y': 4}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 9, 'y': 8}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 6, 'y': 9}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 3, 'y': 9}, {'x': 2, 'y': 9}, {'x': 1, 'y': 9}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 5}], 'latency': '0', 'head': {'x': 7, 'y': 0}, 'length': 32, 'shout': '', 'squad': ''}]}, 'you': {'id': '4bf12628-6a21-49f1-aa52-0e0a1a56fe47', 'name': 'idzol', 'health': 100, 'body': [{'x': 7, 'y': 0}, {'x': 7, 'y': 1}, {'x': 7, 'y': 2}, {'x': 8, 'y': 2}, {'x': 8, 'y': 3}, {'x': 8, 'y': 4}, {'x': 9, 'y': 4}, {'x': 10, 'y': 4}, {'x': 10, 'y': 5}, {'x': 10, 'y': 6}, {'x': 10, 'y': 7}, {'x': 10, 'y': 8}, {'x': 9, 'y': 8}, {'x': 8, 'y': 8}, {'x': 8, 'y': 9}, {'x': 8, 'y': 10}, {'x': 7, 'y': 10}, {'x': 7, 'y': 9}, {'x': 6, 'y': 9}, {'x': 5, 'y': 9}, {'x': 4, 'y': 9}, {'x': 3, 'y': 9}, {'x': 2, 'y': 9}, {'x': 1, 'y': 9}, {'x': 0, 'y': 9}, {'x': 0, 'y': 8}, {'x': 1, 'y': 8}, {'x': 2, 'y': 8}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 2, 'y': 5}, {'x': 2, 'y': 5}], 'latency': '0', 'head': {'x': 7, 'y': 0}, 'length': 32, 'shout': '', 'squad': ''}}],


    # [4,'', '', {}],
    # [4,'', '', {}],
    # [4,'', '', {}],
]

route_performance = [ 
    [801, '', 'performance - four snakes. 11x11', {'game': {'id': 'faa971ad-2dea-4ca0-a25d-c72d3d0c5ffc', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 55, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_tkmyrk8HM3373mqHt9rvcmKW', 'name': 'Cool_as_ice', 'latency': '67', 'health': 93, 'body': [{'x': 3, 'y': 2}, {'x': 2, 'y': 2}, {'x': 2, 'y': 1}, {'x': 3, 'y': 1}, {'x': 4, 'y': 1}], 'head': {'x': 3, 'y': 2}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_KW93qSCq7qM8rXQFBG69kRhQ', 'name': 'Bruddy', 'latency': '206', 'health': 97, 'body': [{'x': 0, 'y': 7}, {'x': 0, 'y': 8}, {'x': 0, 'y': 9}, {'x': 0, 'y': 10}, {'x': 1, 'y': 10}], 'head': {'x': 0, 'y': 7}, 'length': 5, 'shout': '', 'squad': ''}, {'id': 'gs_wJmMFjBg4cfVBWP3F4GvkBHJ', 'name': 'Idzol', 'latency': '500', 'health': 62, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}], 'head': {'x': 3, 'y': 10}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_MmCGy7kCrM9fbD9hppcgkym3', 'name': 'Yung Snek V0', 'latency': '184', 'health': 49, 'body': [{'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 8}, {'x': 2, 'y': 8}], 'head': {'x': 1, 'y': 6}, 'length': 4, 'shout': '', 'squad': ''}], 'food': [{'x': 0, 'y': 6}], 'hazards': []}, 'you': {'id': 'gs_wJmMFjBg4cfVBWP3F4GvkBHJ', 'name': 'Idzol', 'latency': '500', 'health': 62, 'body': [{'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 3, 'y': 8}, {'x': 3, 'y': 7}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}], 'head': {'x': 3, 'y': 10}, 'length': 7, 'shout': '', 'squad': ''}}],
    # 11 x 11 board 
    # 19 x 19 board 
    # 30 x 30 board 
    # 100 x 100 board 
]

route_debug = [  
    # Routing - large lookahead 
    [210, 'right', 'routing - large cavern detection', {'game': {'id': '428b6b8d-6b77-4ef7-9062-4f757157d22d', 'timeout': 500, 'ruleset': {'name': 'solo', 'version': 'cli'}}, 'turn': 282, 'board': {'height': 11, 'width': 11, 'food': [{'x': 1, 'y': 10}, {'x': 9, 'y': 7}, {'x': 0, 'y': 1}, {'x': 8, 'y': 2}, {'x': 9, 'y': 6}], 'hazards': [], 'snakes': [{'id': '7ac156d6-2dc2-4761-988a-6be8e997b772', 'name': 'idzol', 'health': 99, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 8}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 0, 'y': 3}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 4, 'y': 0}, {'x': 5, 'y': 0}, {'x': 6, 'y': 0}, {'x': 7, 'y': 0}, {'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 0}, {'x': 10, 'y': 1}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'latency': '0', 'head': {'x': 5, 'y': 10}, 'length': 40, 'shout': '', 'squad': ''}]}, 'you': {'id': '7ac156d6-2dc2-4761-988a-6be8e997b772', 'name': 'idzol', 'health': 99, 'body': [{'x': 5, 'y': 10}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 6, 'y': 6}, {'x': 6, 'y': 5}, {'x': 5, 'y': 5}, {'x': 4, 'y': 5}, {'x': 3, 'y': 5}, {'x': 2, 'y': 5}, {'x': 1, 'y': 5}, {'x': 1, 'y': 6}, {'x': 1, 'y': 7}, {'x': 1, 'y': 8}, {'x': 0, 'y': 8}, {'x': 0, 'y': 7}, {'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 0, 'y': 3}, {'x': 1, 'y': 3}, {'x': 2, 'y': 3}, {'x': 2, 'y': 4}, {'x': 3, 'y': 4}, {'x': 4, 'y': 4}, {'x': 4, 'y': 3}, {'x': 4, 'y': 2}, {'x': 4, 'y': 1}, {'x': 4, 'y': 0}, {'x': 5, 'y': 0}, {'x': 6, 'y': 0}, {'x': 7, 'y': 0}, {'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 0}, {'x': 10, 'y': 1}, {'x': 10, 'y': 2}, {'x': 10, 'y': 3}, {'x': 10, 'y': 4}], 'latency': '0', 'head': {'x': 5, 'y': 10}, 'length': 40, 'shout': '', 'squad': ''}}],
    
    # Routing - Best path 
    [3, 'down', 'route selection - certain death vs possible death', {'game': {'id': '932cf8ae-de0c-4e63-a89d-7b259f886deb', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 143, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}, {'id': 'gs_DrdpjkdQSmFm6KGYwq7hJVHV', 'name': 'SnakeJS', 'latency': '192', 'health': 98, 'body': [{'x': 0, 'y': 7}, {'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 2, 'y': 6}, {'x': 3, 'y': 6}, {'x': 4, 'y': 6}, {'x': 5, 'y': 6}, {'x': 6, 'y': 6}, {'x': 7, 'y': 6}, {'x': 8, 'y': 6}, {'x': 8, 'y': 7}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}], 'head': {'x': 0, 'y': 7}, 'length': 16, 'shout': '[1 7] --> [0 6]', 'squad': ''}], 'food': [{'x': 0, 'y': 6}, {'x': 1, 'y': 4}], 'hazards': []}, 'you': {'id': 'gs_Ght6cSMdTM94ybFK8PtdPFmb', 'name': 'idzol cloud', 'latency': '155', 'health': 95, 'body': [{'x': 0, 'y': 9}, {'x': 1, 'y': 9}, {'x': 2, 'y': 9}, {'x': 2, 'y': 10}, {'x': 3, 'y': 10}, {'x': 3, 'y': 9}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}, {'x': 6, 'y': 9}, {'x': 6, 'y': 8}, {'x': 6, 'y': 7}, {'x': 7, 'y': 7}, {'x': 7, 'y': 8}, {'x': 7, 'y': 9}], 'head': {'x': 0, 'y': 9}, 'length': 14, 'shout': '', 'squad': ''}}],
    [8,'up', 'enemy eating - certain death vs possible death ', {'game': {'id': '39f5f3fb-c456-4924-9abe-54117b608a12', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 32, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}, {'id': 'gs_CgyqbSwvKSphK6VRmHxrCWVW', 'name': 'moon-snake-pika', 'latency': '192', 'health': 89, 'body': [{'x': 1, 'y': 7}, {'x': 2, 'y': 7}, {'x': 3, 'y': 7}, {'x': 4, 'y': 7}, {'x': 4, 'y': 8}, {'x': 4, 'y': 9}, {'x': 5, 'y': 9}], 'head': {'x': 1, 'y': 7}, 'length': 7, 'shout': '', 'squad': ''}, {'id': 'gs_B3hBgh8SfRXd9dtdff7CQT6F', 'name': 'starter_snake', 'latency': '235', 'health': 100, 'body': [{'x': 0, 'y': 6}, {'x': 0, 'y': 5}, {'x': 0, 'y': 4}, {'x': 1, 'y': 4}, {'x': 1, 'y': 4}], 'head': {'x': 0, 'y': 6}, 'length': 5, 'shout': '', 'squad': ''}], 'food': [{'x': 8, 'y': 7}], 'hazards': []}, 'you': {'id': 'gs_4jTf6trVpHPDr7VmM9h4GKF7', 'name': 'idzol cloud', 'latency': '263', 'health': 97, 'body': [{'x': 1, 'y': 5}, {'x': 2, 'y': 5}, {'x': 3, 'y': 5}, {'x': 4, 'y': 5}, {'x': 5, 'y': 5}, {'x': 5, 'y': 6}], 'head': {'x': 1, 'y': 5}, 'length': 6, 'shout': '', 'squad': ''}}],
    
    # Routing - double eat 
    [900, 'up', 'routing - double eat. avoid tail', {'game': {'id': '89ce373c-b32c-494f-b404-0de4237c85ad', 'ruleset': {'name': 'standard', 'version': 'v1.0.22', 'settings': {'foodSpawnChance': 15, 'minimumFood': 1, 'hazardDamagePerTurn': 0, 'royale': {'shrinkEveryNTurns': 0}, 'squad': {'allowBodyCollisions': False, 'sharedElimination': False, 'sharedHealth': False, 'sharedLength': False}}}, 'timeout': 500, 'source': 'arena'}, 'turn': 89, 'board': {'height': 11, 'width': 11, 'snakes': [{'id': 'gs_KhH8kkKbMPbrhjS9c4cyJrv4', 'name': 'Idzol', 'latency': '417', 'health': 100, 'body': [{'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 7, 'y': 4}], 'head': {'x': 8, 'y': 3}, 'length': 12, 'shout': '', 'squad': ''}, {'id': 'gs_6QhpX7qfTwbtMYj8PxwStx7B', 'name': 'RoboSnake - Panda', 'latency': '184', 'health': 40, 'body': [{'x': 7, 'y': 0}, {'x': 8, 'y': 0}, {'x': 9, 'y': 0}, {'x': 10, 'y': 0}, {'x': 10, 'y': 1}, {'x': 9, 'y': 1}, {'x': 8, 'y': 1}, {'x': 7, 'y': 1}, {'x': 6, 'y': 1}], 'head': {'x': 7, 'y': 0}, 'length': 9, 'shout': '', 'squad': ''}], 'food': [{'x': 5, 'y': 0}, {'x': 7, 'y': 8}, {'x': 4, 'y': 10}, {'x': 7, 'y': 3}], 'hazards': []}, 'you': {'id': 'gs_KhH8kkKbMPbrhjS9c4cyJrv4', 'name': 'Idzol', 'latency': '417', 'health': 100, 'body': [{'x': 8, 'y': 3}, {'x': 9, 'y': 3}, {'x': 10, 'y': 3}, {'x': 10, 'y': 2}, {'x': 9, 'y': 2}, {'x': 8, 'y': 2}, {'x': 7, 'y': 2}, {'x': 6, 'y': 2}, {'x': 6, 'y': 3}, {'x': 6, 'y': 4}, {'x': 7, 'y': 4}, {'x': 7, 'y': 4}], 'head': {'x': 8, 'y': 3}, 'length': 12, 'shout': '', 'squad': ''}}],
   
]

timepanic = CONST.timePanic 

# performance = True 
# silent = True
# route_data = route_survive + route_attack + route_general + route_performance 

performance = False 
silent = False 
route_data = route_debug

total = len(route_data)
success = 0 
fail = 0 
warn = 0
regression = 0
solved = 0

passed_prev = [1, 3, 8, 9, 12, 13, 14, 16, 101, 201, 202, 203, 204, 205, 206, 207, 208, 209]
failed_prev = [2, 4, 5, 6, 7, 10, 11, 15, 801]

regression_list = []
solved_list = []

f = open("env", "w")
f.write("dev:idzol_debug\n")
f.close()

# Record test cases that pass / fail 
passes = []
fails = []

# Performance montior 
profiler = cProfile.Profile()

for data in route_data:
    # Known dataset 
    starttime = time.time()
    # Make move 
    profiler.enable()
    response = handle_move(data[3], silent)
    profiler.disable()
    
    # Measure time 
    endtime = time.time()
    diff = 1000 * (time.time() - starttime) 
    if (diff > timepanic):
        timediff = "{:.2f} ms".format(diff)
        print ("WARN %s. %s exceeds %s ms. Use Case: %s" % (data[0], timediff, timepanic, data[2]))
        warn += 1 

    if response["move"] == '':
        # Performance test 
        pass 

    else:
        if response["move"] in data[1]: 
            # PASS -- Expected result
            # print("PASS %s. Went %s. Expected %s. Strategy: %s" % (str(response["move"]), data[1], data[2]))
            passes.append(data[0])
            success += 1 
            
            if data[0] in failed_prev:
                solved += 1
                print("SOLVED %s. %s" % (data[0], data[1]))
                solved_list.append(data[0])

        else:
            # FAIL -- Unexpected result 
            print("FAIL %s. Went %s. Expected %s. Strategy: %s" % (data[0], str(response["move"]), data[1], data[2]))
            printBoard(data[3])
            fails.append(data[0])
            fail += 1

            if data[0] in passed_prev:
                regression += 1
                print("REGRESSION %s. %s" % (data[0], data[1]))
                regression_list.append(data[0])


if (performance):
    print ("PERFORMANCE SUMMARY")
    print ("===================")
    stats = pstats.Stats(profiler).sort_stats('cumtime')
    # stats.strip_dirs()
    stats.print_stats()
    stats.dump_stats('server_test.prof')
    # run `snakeviz server_test.prof`

print ("TEST SUMMARY")
print ("============")
print ("%d Test cases: %d Pass, %d Fail, %d Warn" % (total, success, fail, warn))
print ("Passed: %s, Failed: %s" % (passes, fails) )
print ("New regressions: %s" % regression_list )
print ("New solves: %s. Remember to update $passed_prev" % solved_list )
